/*
 * This source file was generated by the Gradle 'init' task
 */
package cash.z.f4jumble

import com.google.gson.Gson
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals

class TestVector(
    val normal: String,
    val jumbled: String,
)

// test f4jumble and its inverse f4jumbleinv
class F4jumbleTest {
    @Test
    @OptIn(ExperimentalStdlibApi::class)
    fun vectorsjumblecorrectlytest() {
        val jsonFile = File("src/test/resources/testVectors.json")
        val jsonString = jsonFile.readText()
        val vectors = Gson().fromJson(jsonString, Array<TestVector>::class.java)
        for (vector in vectors) {
            var normalV = vector.normal.hexToByteArray()
            var jumbled = F4jumble.f4Jumble(normalV)

            val jumbledV = vector.jumbled.hexToByteArray()
            var normal = F4jumble.f4JumbleInv(jumbledV)

            assertEquals(jumbledV.toHexString(), jumbled.toHexString())
            assertEquals(normalV.toHexString(), normal.toHexString())
        }
    }
}
